name: Weekly Data Fetch

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write # This grants permission to push changes

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run fetch script
        env:
          UNTALENT_API_TOKEN: ${{ secrets.UNTALENT_API_TOKEN }}
        run: python src/github-actions/01-auto_fetch_api.py

      - name: Run data cleaning script
        run: python src/github-actions/02-clean_data.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/public/raw_jobs_df.csv data/public/clean_jobs_df.csv clean_jobs_df.pkl
          git commit -m "Automated data update: Refresh data files [GitHub Actions]" || exit 0
          git push
